# Generated by Django 2.2.7 on 2019-12-07 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('activation_time', models.DateTimeField()),
                ('card_type', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateTimeField()),
                ('card_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.Card')),
            ],
        ),
    ]
